services:
  db:
    container_name: classroom-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: classroom
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db_data: